spring-boot-security1
DojiDoe/jv-spring-boot-book-store pull request #8
Opened 2024-11-16 17:17 UTC by DojiDoe

2024-11-17 16:42 UTC, Elena-Bruyako requested changes
see comments

2024-11-17 16:42 UTC, Elena-Bruyako commented on pom.xml
> +            <version>3.3.4</version>
```suggestion
```

2024-11-17 16:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Role.java
> +    private RoleName role = RoleName.ROLE_USER;
```suggestion
    private RoleName role;
```

2024-11-17 16:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Role.java
> +@RequiredArgsConstructor
```suggestion
```

2024-11-17 16:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-11-17 16:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    private Set<Role> roles;
```suggestion
    private Set<Role> roles = new HashSet<>();
```

2024-11-17 16:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("Can't find user by email"));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Can't find user by email"));
```

2024-11-17 16:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
> +        requestDto.setPassword(passwordEncoder.encode(requestDto.getPassword()));
set password to User user, not dto

2024-11-17 16:42 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
>      @Override
```suggestion
    @Override
    @Transactional
```

2024-11-17 16:42 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +                  type: ENUM('ROLE_ADMIN','ROLE_USER','ROLE_MANAGER')
bad approach to add enum here, it will cause some problems during modify it

2024-11-18 21:34 UTC, sarakhmen approved these changes
lgtm!

2024-11-21 11:16 UTC, merged