spring-boot-security-jwt-1
DojiDoe/jv-spring-boot-book-store pull request #9
Opened 2024-11-26 16:34 UTC by DojiDoe

2024-11-26 17:31 UTC, JJJazl requested changes

2024-11-26 17:31 UTC, JJJazl commented on src/main/java/mate/academy/bookstore/security/AuthenticationService.java
> +
```suggestion
```

2024-11-26 17:31 UTC, JJJazl commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +        }
Move these values to the constants

2024-11-26 17:31 UTC, JJJazl commented on src/main/java/mate/academy/bookstore/security/JwtUtil.java
> +    }
```suggestion
    private final long expiration;

    public JwtUtil(@Value("${jwt.secret}") String secretString, @Value("${jwt.expiration}") long expiration) {
        this.secret = Keys.hmacShaKeyFor(secretString.getBytes(StandardCharsets.UTF_8));
        this.expiration = expiration;
    }
```

2024-11-27 06:59 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few minor comments ;)

2024-11-27 06:59 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
annotation Valid missed

2024-11-27 06:59 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(AUTHORIZATION);
```suggestion
        String bearerToken = request.getHeader(HttpHeader.AUTHORIZATION);
```

2024-11-27 06:59 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/security/JwtUtil.java
> +
```suggestion
```

2024-11-27 06:59 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/security/JwtUtil.java
> +    private Key secret;
```suggestion
    private final SecretKey secret;
```

2024-11-27 12:50 UTC, Elena-Bruyako requested changes
see comments

2024-11-27 12:50 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/AuthenticationController.java
> +    @PostMapping("/login")
add swagger annotations to controller

2024-11-27 12:50 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/HttpHeader.java
> +    public static final String AUTHORIZATION = "Authorization";
remove, you can use Spring constant

2024-11-27 12:50 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +    public static final int BEGIN_INDEX = 7;
```suggestion
```

2024-11-27 12:50 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(HttpHeader.AUTHORIZATION);
import from `import org.springframework.http.HttpHeaders;`

```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-11-27 12:50 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(BEGIN_INDEX);
```suggestion
            return bearerToken.substring(BEARER.length());
```

2024-11-27 13:13 UTC, Elena-Bruyako approved these changes

2024-11-27 13:21 UTC, merged